board/urls.py
from django.urls import path, re_path
from board.views import *
from django.contrib import admin

app_name = 'board'

urlpatterns = [
    path('<int:pk>', BoardView.as_view(), name='board'),
    path('board_detail/<int:pk>', BoardViewDV.as_view(), name='board_detail'),
    path('board_add/<int:fk>/', BoardCreateView.as_view(), name="board_add"),
    path('board_update/<int:pk>/', BoardUpdateView.as_view(), name="board_update"),
    path('board_delete/<int:pk>/', BoardDeleteView.as_view(), name="board_delete"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('board/', include('board.urls')),
    path('notice/', include('notice.urls')),
    # 로그인, 로그아웃, 비밀번호 변경 등 담당
    path('accounts/', include('django.contrib.auth.urls')),
    # 회원 가입 및 처리
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(),name='register_done'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from market.models import Market


from taggit.managers import TaggableManager

class Board(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50,)
    content = models.TextField('CONTENT')
    registered_date = models.DateTimeField('CREATE DATE', auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)
    market = models.ForeignKey(Market, on_delete=models.CASCADE)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

    class Meta:
        verbose_name = 'board'

        verbose_name_plural = 'boards'
        db_table = 'board'  # 테이블명 재정의
        ordering = ('-modify_dt',)  # orderby 절, -이면 내림차순

    def __str__(self):
        return self.title

board/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from board.models import Board, models
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, \
    TodayArchiveView
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from mysite.views import OwnerOnlyMixin
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from market.models import Market, Store, MarketAttachFile, StoreAttachFile, StoreComment


# TemplateView
class BoardView(ListView):
    model = Board

    def get(self, request, *args, **kwargs):
        queryset = Board.objects.filter(market_id=kwargs['pk']).order_by('id')
        page = int(request.GET.get('p', 1))
        paginator = Paginator(queryset, 5)
        boards = paginator.get_page(page)

        ctx = {
            'boards': boards,
            'market_fk': kwargs['pk'],

        }
        return render(request, 'board_list.html', ctx)


class BoardViewDV(DetailView):
    def get(self, request, *args, **kwargs):
        queryset = Board.objects.get(pk=kwargs['pk'])
        ctx={
            'board': queryset,
        }
        return render(request, 'board_detail.html', ctx)


class BoardCreateView(LoginRequiredMixin, CreateView):
    model = Board
    template_name = 'board_form.html'
    fields = ['title', 'content']

    success_url = reverse_lazy('market:home')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.market = Market.objects.get(pk=self.kwargs.get('fk'))
        # form.instance.modify_dt = timezone.now()  # 업데이트 시간 버그 문제
        response = super().form_valid(form)  # Post 모델 저장, self.object
        return response



class BoardUpdateView(OwnerOnlyMixin, UpdateView):
    model = Board
    template_name = 'board_form.html'
    fields = ['title', 'content']
    success_url = reverse_lazy('market:home')

    def form_valid(self, form):
        return super().form_valid(form)


class BoardDeleteView(OwnerOnlyMixin, DeleteView):
    model = Board
    success_url = reverse_lazy('market:home')
    template_name = 'board_confirm_delete.html'

board/templates/board_confirm_delete.html
{% extends "base.html" %}
{% block title %}게시글 삭제{% endblock %}
{% block content %}
<style>
.content {
text-align: center;
height: 30%;
width: 30%;
}
</style>

<div class="content">
    <h1>게시글 삭제</h1>
<br>
<form action="." method="post">{% csrf_token %}
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
</form>
</div>
{% endblock %}

board/templates/board_detail.html
{% extends "base.html" %}
{% block title %}store_detail.html{% endblock %}

{% block content %}
<link href="http://fonts.googleapis.com/earlyaccess/hanna.css" rel="stylesheet">
<style>
    .content {
        text-align: center;
        height: 73%;
        width: 50%;
        overflow-y: scroll;
        -ms-overflow-style: none;  /* IE and Edge */
        scrollbar-width: none;  /* Firefox */
    }
        .content::-webkit-scrollbar {
         display: none;
    }

.card {
  box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
  transition: all 0.2s ease-in-out;
  box-sizing: border-box;
  margin-top:10px;
  margin-bottom:10px;
}
.target1 { display: inline-block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.hn{font-family: 'Hanna', sans-serif;}
.card > .card-inner {
  padding:10px;
}

textarea.form-control{
	width:100%;
	height:200px;
	color: black;
    resize:none;

}

</style>

<div class="content hn">
    <div class="container-fluid">
        <div class="row">
            <!--              2번째 카드-->
            <div class="col-sm-12">
                <div class="card border-0" style="background-color:rgba(120,190,40,0.8); color:white;">
                    <div class="card-inner">
                        <div class="header text-left">
                            <div class="form-group"><br>
                                <h1 style="font-weight:bold;">{{board.title}}</h1><br>
                                <h4>글쓴이 : {{board.owner}}</h4><br>
                                <h4>작성시간 : {{board.registered_date}}</h4><br>
                                <h4>내용</h4>
                                <textarea class="form-control" readonly>{{board.content}}</textarea>
                            </div>
                            <div class="text-left">
                                <!--                                권한 추가시 표시할 부분-->
                                <a href="{% url 'board:board_update' board.id %}" class="mr-3">
                                    <i class="far fa-edit"></i> 수정</a>
                                <a href="{% url 'board:board_delete' board.id %}" class="text-danger mr-3">
                                    <i class="fas fa-trash"></i> 삭제</a>
                            </div>
                            <br>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>            <!--              2번째 카드 끝-->

</div>

</div>
</div>

{% endblock %}

board/templates/board_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}store_detail.html{% endblock %}

{% block content %}
<style>
.content {
text-align: center;
height: 55%;
width: 50%;
color:black;
font-size:1.5em
}
::placeholder {
color:#000;
font-size:1.1em;
}

.form-group{
font-weight: bold;
font-size:1.1em;
}

div.center {
width: 100%;
float: center;
}

select {
display: black;
}

textarea {
width:100%;
height: 13rem;
resize:none;
}

</style>
<div class="content">
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h1 style="font-weight:bold;">게시글 작성 - {{user}}</h1>
        {% if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">
                {{ form.errors }}
            </div>
        </div>
        {% endif %}
        <div class="center">
            <div class="form-group row">
                제목 {{ form.title }}
            </div>
            <div class="form-group row">
                내용 : {{ form.content }}
            </div>
            <div class="form-group row">
                <input type="submit" value="제출" class="btn btn-info"/>
            </div>
        </div>
    </form>
</div>
{% endblock %}

board/templates/board_list.html
{% extends "base.html" %}
{% block title %}board_list.html{% endblock %}
{% block content %}
<link href="http://fonts.googleapis.com/earlyaccess/hanna.css" rel="stylesheet">
<style>
.content {
text-align: center;
height: 60%;
width: 50%;
}
.table{
font-size:1.2em;

}
td{
text-align:center;
}
#store:hover tbody tr:hover td {
background: rgba(255,255,255,0.5);
color:white;
}
.hn{font-family: 'Hanna', sans-serif;}
.target1 { display: inline-block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
</style>


<div class="content hn">
    <div class="row">
        <div class="col-lg-12">
            <div class="card" style="background-color:rgba(140,200,50,0.6);">
                <div class="card-header card-header-success" style="text-align: left;"></div>

                <div class="card-body table-responsive" style="padding-top:0;">
                    <table id="store" class="table table-hover" style="margin-bottom:0;">
                        <thead class="text-dark">
                        <tr>
                            <td class="target1" style="padding:0.2rem;width:50%;">제목</td>
                            <td class="target1" style="padding:0.2rem;width:10%;">작성자</td>
                            <td class="target1" style="padding:0.2rem;width:40%;">등록시간</td>
                        </tr>
                        </thead>

                        <tbody>
                        {% for board in boards %}
                        <tr onclick="location.href='{% url 'board:board_detail' board.id %}'">
                            <td class="target1" style="padding:0.2rem;width:50%;">{{board.title}}</td>
                            <td class="target1" style="padding:0.2rem;width:10%;">{{board.owner}}</td>
                            <td class="target1" style="padding:0.2rem;width:40%;">{{board.registered_date}}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% if user.is_active %}
                    <div class="text-right mr-3">
                        <a href="{% url 'board:board_add' market_fk%}" class="btn btn-primary btn-sm">
                            <i class="fas fa-pencil-alt"></i> 쓰기</a>
                    </div>
                    {% endif %}
                    <ul class="pagination justify-content-center">
                        {% if boards.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?p={{boards.previous_page_number}}">이전</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link disabled" href="#">이전</a>
                        </li>
                        {% endif %}

                        <li class="page-item active">
                            <a class="page-link">{{boards.number}}/{{boards.paginator.num_pages}}</a>
                        </li>

                        {% if boards.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?p={{boards.next_page_number}}">다음</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link disabled" href="#">다음</a>
                        </li>
                        {% endif %}
                    </ul>


                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}