board/urls.py
from django.urls import path, re_path
from board.views import *
from django.contrib import admin

app_name = 'board'

urlpatterns = [
    path('<int:pk>', BoardView.as_view(), name='board'),
    path('board_detail/<int:pk>', BoardViewDV.as_view(), name='board_detail'),
    path('board_add/<int:fk>/', BoardCreateView.as_view(), name="board_add"),
    path('board_update/<int:pk>/', BoardUpdateView.as_view(), name="board_update"),
    path('board_delete/<int:pk>/', BoardDeleteView.as_view(), name="board_delete"),
]

market/urls.py
from django.urls import path
from market.views import StoreDV, StoreLV, StoreCreateView, StoreUpdateView, StoreDeleteView, store_download, store_comment
from market.views import MarketDV, MarketCreateView, MarketUpdateView, MarketDeleteView, market_download,MarketDetail
from mysite.views import HomeView
from market.models import Market, Location

app_name = 'market'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('<int:pk>/', MarketDV.as_view(), name='market'),
    path('market_detail/<int:pk>/', MarketDetail.as_view(), name='market_detail'),
    path('market_add/', MarketCreateView.as_view(), name="market_add"),
    path('<int:pk>/market_update/', MarketUpdateView.as_view(), name="market_update"),
    path('<int:pk>/market_delete/', MarketDeleteView.as_view(), name="market_delete"),
    path('market_download/<int:id>', market_download, name="market_download"),

    path('store/<int:pk>/', StoreLV.as_view(), name='store'),
    path('store/<int:fk>/<int:pk>/', StoreDV.as_view(), name='store_detail'),
    path('<int:fk>/store_add/', StoreCreateView.as_view(), name="store_add"),
    path('<int:pk>/store_update/', StoreUpdateView.as_view(), name="store_update"),
    path('<int:pk>/store_delete/', StoreDeleteView.as_view(), name="store_delete"),
    path('store_download/<int:id>', store_download, name="store_download"),
    path('comment/<int:fk>/<int:pk>', store_comment, name='store_comment'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('board/', include('board.urls')),
    path('notice/', include('notice.urls')),
    # 로그인, 로그아웃, 비밀번호 변경 등 담당
    path('accounts/', include('django.contrib.auth.urls')),
    # 회원 가입 및 처리
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(),name='register_done'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class Location(models.Model):
    location = models.CharField(max_length=50, verbose_name="지역")

    def __str__(self):
        return self.location

    class Meta:
        db_table = "location"
        verbose_name = "지역"
        verbose_name_plural = "지역"


class Market(models.Model):

    market_name = models.CharField(verbose_name="시장이름", max_length=100)
    address = models.CharField(null=True, max_length=100)
    products = models.CharField(null=True, max_length=200)
    tel = models.CharField(null=True, max_length=100)
    sights_info = models.CharField(null=True, max_length=200)
    closed_date = models.CharField(null=True, max_length=200)
    hour_info = models.CharField(null=True, max_length=100)
    park_info = models.CharField(null=True, max_length=200)
    products = models.CharField(null=True, max_length=200)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    def __str__(self):
        return self.market_name

    class Meta:
        db_table = "market_list"
        verbose_name = "시장목록"
        verbose_name_plural = "시장목록"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.market_name, allow_unicode=True)
        super().save(*args, **kwargs)

class Store(models.Model):
    store_name = models.CharField('STORE NAME', max_length=100)
    store_introduction = models.CharField('STORE INTRODUCTION', null=True, max_length=100)
    open_hour = models.TimeField('OPEN HOUR', blank=True, default='00:00:00')
    close_hour = models.TimeField('CLOSE HOUR', blank=True, default='23:59:59')
    hour_information = models.CharField('HOUR INFORMATION', blank=True, null=True, max_length=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)
    market_list = models.ForeignKey(Market, on_delete=models.CASCADE)

    class Meta:
        db_table = "store_list"
        verbose_name = "점포목록"
        verbose_name_plural = "점포목록"

    def __str__(self):
        return self.store_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.store_name, allow_unicode=True)
        super().save(*args, **kwargs)


class MarketAttachFile(models.Model):
    market = models.ForeignKey(Market, on_delete=models.CASCADE, related_name="files", verbose_name='market', blank=True, null=True)
    upload_file = models.FileField(upload_to="%Y/%m/%d", null=True, blank=True, verbose_name="파일")
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')
    content_type = models.CharField(max_length=128, null=True, verbose_name='MIME TYPE')
    size = models.IntegerField('파일크기')

    class Meta:
        db_table = "market_attach_file"

    def __str__(self):
        return self.filename


class StoreAttachFile(models.Model):
    post = models.ForeignKey(Store, on_delete=models.CASCADE,
                             related_name="files",
                             verbose_name='Store', blank=True, null=True)
    upload_file = models.FileField(upload_to="%Y/%m/%d",
                                   null=True, blank=True, verbose_name='파일')
    filename = models.CharField(max_length=64, null=True,
                                verbose_name='첨부파일명')
    content_type = models.CharField(max_length=128, null=True,
                                    verbose_name='MIME TYPE')
    size = models.IntegerField('파일 크기')

    class Meta:
        db_table = "store_attach_file"

    def __str__(self):
        return self.filename


class StoreComment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    comment = models.TextField(verbose_name="댓글내용")
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name="등록 시간")
    score = models.IntegerField(null=True)

    def __str__(self):
        return self.comment

    class Meta:
        db_table = "store_comment"

market/views.py
from django.shortcuts import render, get_object_or_404, redirect
from market.models import Market, Store, MarketAttachFile, StoreAttachFile, StoreComment
from django.views.generic import TemplateView, DetailView, View
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from mysite.views import OwnerOnlyMixin
from django.http import FileResponse
import os
from django.conf import settings
from django.core.paginator import Paginator
import json
import urllib.request
from django.utils import timezone


class MarketDetail(DetailView):
    def get(self, request, *args, **kwargs):
        queryset = get_object_or_404(Market, pk=kwargs['pk'])
        ctx = {
            'market': queryset
        }
        return render(request, 'market/market_detail.html', ctx)


class MarketDV(View):

    def get(self, request, *args, **kwargs):
        queryset3 = get_object_or_404(Market, pk=kwargs['pk'])
        # 네이버 블로그 크롤링 추가
        client_id = "un73j8VyJzJJfWpGfFWD"
        client_secret = "FPdfimL0ui"

        q = queryset3.market_name  # 시장이름으로만 블로그 내에 검색
        encText = urllib.parse.quote(q)
        url = "https://openapi.naver.com/v1/search/blog?query=" + encText + "&display=4"  # json 결과, 출력결과 4개
        market_request = urllib.request.Request(url)
        market_request.add_header("X-Naver-Client-Id", client_id)
        market_request.add_header("X-Naver-Client-Secret", client_secret)
        response = urllib.request.urlopen(market_request)
        rescode = response.getcode()

        if (rescode == 200):
            response_body = response.read()
            result = json.loads(response_body.decode('utf-8'))
            items = result.get('items')

            context = {
                'items': items,  # 크롤링 검색 결과
                'market_detail': queryset3
            }
            return render(request, 'market/market.html', context=context)


class MarketCreateView(LoginRequiredMixin, CreateView):
    model = Market
    template_name = 'market/market_form.html'
    # introduction 빠져서 임시적인 주석처리
    # fields = ['market_name', 'introduction', 'location']
    fields = '__all__'

    def get_success_url(self):
        return reverse('market:market', kwargs={'pk': self.object.pk})

    def form_valid(self, form):

        form.instance.owner = self.request.user
        response = super().form_valid(form)

        files = self.request.FILES.getlist("files")
        for file in files:
            attach_file = MarketAttachFile(market=self.object, filename=file.name, size=file.size,
                                           content_type=file.content_type, upload_file=file)
            attach_file.save()
        return response


class MarketUpdateView(OwnerOnlyMixin, UpdateView):
    model = Market
    fields = '__all__'

    def get_success_url(self):
        return reverse('market:market', kwargs={'pk': self.object.pk})


    def form_valid(self, form):
        form.instance.owner = self.request.user


        # 파일 삭제
        # delete_files = self.request.POST["delete_files"]
        delete_files = self.request.POST.getlist("delete_files")
        for fid in delete_files:  # fid는 문자열 타입임
        # 실제 파일 삭제 및 PostAttachFile 삭제
            file = MarketAttachFile.objects.get(id=int(fid))
            file_path = os.path.join(settings.MEDIA_ROOT, str(file.upload_file))
            os.remove(file_path)  # 실제 파일 삭제
            file.delete()  # 모델 삭제(테이블의 행 삭제)


        response = super().form_valid(form)  # Post 모델 저장, self.object

        # 업로드 파일 얻기
        files = self.request.FILES.getlist("files")
        for file in files:
            attach_file = MarketAttachFile(market=self.object, filename=file.name, size=file.size, content_type=file.content_type, upload_file=file)
            attach_file.save()
        return response

class MarketDeleteView(OwnerOnlyMixin, DeleteView):
    model = Market
    success_url = reverse_lazy('market:home')



class StoreLV(ListView):
    model = Store

    def get(self, request, *args, **kwargs):
        queryset = Store.objects.filter(market_list_id=kwargs['pk']).order_by('id')
        page = int(request.GET.get('p', 1))
        paginator = Paginator(queryset, 5)
        boards = paginator.get_page(page)

        ctx = {
            'boards': boards,
            'market_fk': kwargs['pk'],

        }
        return render(request, 'market/store_list.html', ctx)


class StoreDV(DetailView):
    def get(self, request, *args, **kwargs):
        queryset = StoreComment.objects.filter(store_id=kwargs['pk'])
        queryset2 = Store.objects.get(pk=kwargs['pk'])

        page = int(request.GET.get('p', 1))     # 댓글 페이징
        paginator = Paginator(queryset, 4)
        commments = paginator.get_page(page)

        ctx={
            'comments': commments,
            'store': queryset2,
        }
        return render(request, 'market/store_detail.html', ctx)


class StoreCreateView(LoginRequiredMixin, CreateView):
    model = Store
    template_name = 'market/store_form.html'
    fields = ['store_name', 'store_introduction', 'open_hour', 'close_hour', 'hour_information']
    success_url = reverse_lazy('market:home')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.market_list = Market.objects.get(pk=self.kwargs.get('fk'))
        # form.instance.modify_dt = timezone.now()  # 업데이트 시간 버그 문제
        response = super().form_valid(form)  # Post 모델 저장, self.object

        # 업로드 파일 얻기
        files = self.request.FILES.getlist("files")
        for file in files:
            attach_file = StoreAttachFile(post=self.object, filename=file.name,
                                          size=file.size, content_type=file.content_type,
                                          upload_file=file)
            attach_file.save()
        return response

        # return super().form_valid(form)



class StoreUpdateView(OwnerOnlyMixin, UpdateView):
    model = Store
    fields = ['store_name', 'store_introduction', 'open_hour', 'close_hour', 'hour_information']
    success_url = reverse_lazy('market:home')


    def form_valid(self, form):
        form.instance.owner = self.request.user

        # 파일 삭제
        # delete_files = self.request.POST["delete_files"]
        delete_files = self.request.POST.getlist("delete_files")
        for fid in delete_files:  # fid는 문자열 타입임
        # 실제 파일 삭제 및 PostAttachFile 삭제
            file = StoreAttachFile.objects.get(id=int(fid))
            file_path = os.path.join(settings.MEDIA_ROOT, str(file.upload_file))
            os.remove(file_path)  # 실제 파일 삭제
            file.delete()  # 모델 삭제(테이블의 행 삭제)

        response = super().form_valid(form)  # Post 모델 저장, self.object

        # 업로드 파일 얻기
        files = self.request.FILES.getlist("files")
        for file in files:
            attach_file = StoreAttachFile(post=self.object, filename=file.name, size=file.size, content_type=file.content_type, upload_file=file)
            attach_file.save()
        return response

class StoreDeleteView(OwnerOnlyMixin, DeleteView):
    model = Store
    success_url = reverse_lazy('market:home')


def market_download(request, id):
    file = MarketAttachFile.objects.get(id=id)
    file_path = os.path.join(settings.MEDIA_ROOT, str(file.upload_file))
    return FileResponse(open(file_path, 'rb'))


def store_download(request, id):
    file = StoreAttachFile.objects.get(id=id)
    file_path = os.path.join(settings.MEDIA_ROOT, str(file.upload_file))
    return FileResponse(open(file_path, 'rb'))


# 댓글 등록 함수
def store_comment(request, pk, fk):
    store = Store.objects.get(pk=pk)
    comments = StoreComment()
    comments.author = request.user
    comments.comment = request.GET['comments']
    comments.registered_date = timezone.datetime.now()
    comments.score = request.GET['score']
    comments.store = store
    comments.save()
    return redirect('market:store_detail', fk, pk)

market/templates/market/market_confirm_delete.html
{% extends "base.html" %}
{% block title %}market_confirm_delete.html{% endblock %}
{% block content %}



<style>
.content {
text-align: center;
height: 30%;
width: 30%;
}
</style>

<div class="content hn">
    <h1>시장 삭제</h1>
<br>
<form action="." method="post">{% csrf_token %}
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
</form>
</div>
{% endblock %}

market/templates/market/market_detail.html
{% extends "base.html" %}
{% block title %}시장소개{% endblock %}

{% block content %}

<style>
    .content {
        text-align: center;
        height: 70%;
        width: 70%;
        overflow-y: scroll;
        -ms-overflow-style: none;  /* IE and Edge */
        scrollbar-width: none;  /* Firefox */
    }
        .content::-webkit-scrollbar {
         display: none;
    }

    .container-wrap>.container .row {
        background: #ff0;
        height: 100%;
        width: 100%;
        text-align: center;
    }

    .container>.row {
        background: #FF0000;

    }

    .container-wrap>.blank {
        height: 3px;
        width: 1px;
        background: #B2EBF4;
    }


.card {
  box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
  transition: all 0.2s ease-in-out;
  box-sizing: border-box;
  margin-top:10px;
  margin-bottom:10px;
}


.card > .card-inner {
  padding:10px;
}
.card .header h2, h3 {
  margin-bottom: 0px;
  margin-top:0px;
}
.card .header {
  margin-bottom:5px;
}
.card img{
  width:100%;
}



</style>

<div class="content hn">
    <div class="container-fluid">
        <div class="row">
            <!--              1번째 카드-->
            <div class="col-sm-4">
                <div class="card border-0" style="background-color:rgba(38,94,171,0); box-shadow:none;">
                    <div class="image">
                        <!--첨부파일이 없으면 기본 이미지 있으면 대표사진-->
                        {% if market.files.get.id %}
                        <img src="{% url 'market:market_download' market.files.get.id %}">
                        {% else %}
                        <img class="card-img-top" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/210284/flex-1.jpg">
                        {% endif %}
                        <!--첨부파일이 없으면 기본 이미지 있으면 대표사진 여기까지-->
                    </div>
                    <div class="card-inner">
                        <div class="header">
                            <h2>{{market.market_name}}</h2>
                        </div>
                        <div>
                            <div class="text-right">
<!--                                권한 추가시 표시할 부분-->
                                <a href="{% url 'market:market_update' market.id %}" class="mr-3">
                                    <i class="far fa-edit"></i> 수정</a>
                                <a href="{% url 'market:market_delete' market.id %}" class="text-danger mr-3">
                                    <i class="fas fa-trash"></i> 삭제</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--              1번째 카드 끝-->
            <!--              2번째 카드-->
            <div class="col-sm-8">
                <div class="card" style="background-color:rgba(50,100,180,0.6); color:white;">
                    <div class="card-inner">
                        <div class="card-header card-header-success" style="text-align:left;">
                        <i class="fas fa-sign-in-alt"></i><span class="hn"> 시장 정보</span></div>
                    <div class="card-body table-responsive" style="padding-top:2px;">
                        <table class="table table-hover" style="margin-bottom:2px;">
                            <tbody>
                                <tr style="color:white;"><td style="padding:0.2rem;width:30%;">주소</td><td style="padding:0.2rem;width:70%;">{{market.address}}</td></tr>
                                <tr style="color:white;"><td style="padding:0.2rem;width:30%;">전화번호</td><td style="padding:0.2rem;width:70%;">{{market.tel}}</td></tr>
                                <tr style="color:white;"><td style="padding:0.2rem;width:30%;">영업시간</td><td style="padding:0.2rem;width:70%;">{{market.hour_info}}</td></tr>
                                <tr style="color:white;"><td style="padding:0.2rem;width:30%;">휴무일</td><td style="padding:0.2rem;width:70%;">{{market.closed_date}}</td></tr>
                                <tr style="color:white;"><td style="padding:0.2rem;width:30%;">판매품목</td><td style="padding:0.2rem;width:70%;">{{market.products}}</td></tr>
                                <tr style="color:white;"><td style="padding:0.2rem;width:30%;">주차여부</td><td style="padding:0.2rem;width:70%;">{{market.park_info}}</td></tr>
                                <tr style="color:white;"><td style="padding:0.2rem;width:30%;">주변 관광지</td><td style="padding:0.2rem;width:70%;">{{market.sights_info}}</td></tr>
                            </tbody>
                        </table>
                </div>
            </div>            <!--              2번째 카드 끝-->

        </div>

    </div>
</div>

{% endblock %}

market/templates/market/store_confirm_delete.html
{% extends "base.html" %}
{% block title %}store_confirm_delete.html{% endblock %}
{% block content %}



<style>
.content {
text-align: center;
height: 30%;
width: 30%;
}
</style>

<div class="content hn">
    <h1>점포 삭제</h1>
<br>
<form action="." method="post">{% csrf_token %}
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
</form>
</div>
{% endblock %}

market/templates/market/store_detail.html
{% extends "base.html" %}
{% block title %}점포안내{% endblock %}

{% block content %}

<style>
    .content {
        text-align: center;
        height: 70%;
        width: 70%;
                overflow-y: scroll;
          -ms-overflow-style: none;  /* IE and Edge */
           scrollbar-width: none;  /* Firefox */
    }
    .content::-webkit-scrollbar {
         display: none;
    }


    .container-wrap>.container .row {
        background: #ff0;
        height: 100%;
        width: 100%;
        text-align: center;
    }

    .container>.row {
        background: #FF0000;

    }

    .container-wrap>.blank {
        height: 3px;
        width: 1px;
        background: #B2EBF4;
    }


.card {
  box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
  transition: all 0.2s ease-in-out;
  box-sizing: border-box;
  margin-top:10px;
  margin-bottom:10px;
  background-color:#FFF;
}


.card > .card-inner {
  padding:10px;
}
.card .header h2, h3 {
  margin-bottom: 0px;
  margin-top:0px;
}
.card .header {
  margin-bottom:5px;
}
.card img{
  width:100%;
}

textarea {
width:100%;
height: 2rem;
background-color: #fff;
color: black;
}

label{
color:white;

}



</style>

<div class="content hn">
    <div class="container-fluid">
        <div class="row">
            <!--              1번째 카드-->
            <div class="col-sm-4">
                <div class="card border-0" style="background-color:rgba(38,94,171,0); box-shadow:none;">
                    <div class="image">
                        <!--첨부파일이 없으면 기본 이미지 있으면 대표사진-->
                        {% if store.files.get.id %}
                        <img src="{% url 'market:store_download' store.files.get.id %}">
                        {% else %}
                        <img class="card-img-top" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/210284/flex-1.jpg">
                        {% endif %}
                        <!--첨부파일이 없으면 기본 이미지 있으면 대표사진 여기까지-->
                    </div>
                    <div class="card-inner">
                        <div class="header">
                            <h2>{{store.market_list}}</h2>
                            <h4>{{store.store_name}}</h4>
                        </div>
                        <div>
                            <div class="text-right">
                                <!--                                권한 추가시 표시할 부분-->
                                <a href="{% url 'market:store_update' store.id %}" class="mr-3">
                                    <i class="far fa-edit"></i> 수정</a>
                                <a href="{% url 'market:store_delete' store.id %}" class="text-danger mr-3">
                                    <i class="fas fa-trash"></i> 삭제</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--              1번째 카드 끝-->
            <!--              2번째 카드-->
            <div class="col-sm-8">
                <div class="card" style="background-color:rgba(30,190,240,0.8);">
                    <div class="card-inner">
                        <div class="header text-left" style="color:white;">
                            <h4>{{store.introduction}}</h4>
                            <h4>OPEN : {{store.open_hour}}</h4>
                            <h4>CLOSE : {{store.open_hour}}</h4>
                            <h4>휴무일 : {{store.hour_information}}</h4>
                        </div>
                        <h4 style="color:white;">사용자 이용후기</h4>
                        <div class="text-left" style="color:white;">
                            <table class="table table-hover" style="margin-bottom:0;">
                                <tbody>
                                {% for comment in comments %}
                                <tr style="color:white;">
                                    <td style="padding:0.65rem;">{{ comment.comment }}</td>
                                    <td style="padding:0.65rem;">{{ comment.score }}</td>
                                </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                            <ul class="pagination justify-content-center">
                                {% if comments.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?p={{comments.previous_page_number}}">이전</a>
                                </li>
                                {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link disabled" href="#">이전</a>
                                </li>
                                {% endif %}

                                <li class="page-item active">
                                    <a class="page-link">{{comments.number}}/{{comments.paginator.num_pages}}</a>
                                </li>

                                {% if comments.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?p={{comments.next_page_number}}">다음</a>
                                </li>
                                {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link disabled" href="#">다음</a>
                                </li>
                                {% endif %}
                            </ul>

                            <form action="{% url 'market:store_comment' store.market_list_id store.id %}">

                                <div>
                                    <input type="radio" id="contactChoice1"
                                           name="score" value="1">
                                    <label for="contactChoice1">1</label>

                                    <input type="radio" id="contactChoice2"
                                           name="score" value="2">
                                    <label for="contactChoice2">2</label>

                                    <input type="radio" id="contactChoice3"
                                           name="score" value="3">
                                    <label for="contactChoice3">3</label>

                                    <input type="radio" id="contactChoice4"
                                           name="score" value="4">
                                    <label for="contactChoice4">4</label>

                                    <input type="radio" id="contactChoice5"
                                           name="score" value="5">
                                    <label for="contactChoice5">5</label>


                                </div>
                                <textarea name="comments" style="resize:none;"></textarea>

                                <button type="submit" style="color:black;">댓글등록</button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>            <!--              2번째 카드 끝-->

        </div>

    </div>
</div>

{% endblock %}

market/templates/market/store_list.html
{% extends "base.html" %}
{% block title %}점포목록{% endblock %}
{% block content %}
<style>
.content {
text-align: center;
height: 60%;
width: 50%;
}
.table{
font-size:1.2em;

}
td{
text-align:center;
}
#store:hover tbody tr:hover td {
background: rgba(255,255,255,0.5);
color:white;
}

</style>


<div class="content hn">
    <div class="row">
        <!--              2번째 열 2번째 카드 시작-->
        <div class="col-lg-12">
            <div class="card" style="background-color:rgba(40,200,250,0.6);">
                <div class="card-header card-header-success" style="text-align: left;"></div>

                <div class="card-body table-responsive" style="padding-top:0;">
                    <table id="store" class="table table-hover" style="margin-bottom:0;">
                        <thead class="text-dark">
                        <th>점포명</th>
                        <th>오픈시간</th>
                        <th>종료시간</th>
                        </thead>

                        <tbody>
                        {% for store in boards %}
                        <tr onclick="location.href='/market/store/{{store.market_list.id}}/{{store.id}}'">
                            <td>{{store.store_name}}</td>
                            <td>{{store.open_hour}}</td>
                            <td>{{store.close_hour}}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% if user.is_active %}
                    <div class="text-right mr-3">
                        <a href="{% url 'market:store_add' market_fk%}" class="btn btn-primary btn-sm">
                            <i class="fas fa-pencil-alt"></i> 쓰기</a>
                    </div>
                    {% endif %}
                    <ul class="pagination justify-content-center">
                        {% if boards.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?p={{boards.previous_page_number}}">이전</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link disabled" href="#">이전</a>
                        </li>
                        {% endif %}

                        <li class="page-item active">
                            <a class="page-link">{{boards.number}}/{{boards.paginator.num_pages}}</a>
                        </li>

                        {% if boards.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?p={{boards.next_page_number}}">다음</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link disabled" href="#">다음</a>
                        </li>
                        {% endif %}
                    </ul>


                </div>
            </div>
        </div>
        <!--              2번째 열 2번째 카드 끝-->
    </div>

</div>
{% endblock %}