board/urls.py
from django.urls import path, re_path
from board.views import *
from django.contrib import admin

app_name = 'board'

urlpatterns = [
    path('<int:pk>', BoardView.as_view(), name='board'),
    path('board_detail/<int:pk>', BoardViewDV.as_view(), name='board_detail'),
    path('board_add/<int:fk>/', BoardCreateView.as_view(), name="board_add"),
    path('board_update/<int:pk>/', BoardUpdateView.as_view(), name="board_update"),
    path('board_delete/<int:pk>/', BoardDeleteView.as_view(), name="board_delete"),
]

market/urls.py
from django.urls import path
from market.views import StoreDV, StoreLV, StoreCreateView, StoreUpdateView, StoreDeleteView, store_download, store_comment
from market.views import MarketDV, MarketCreateView, MarketUpdateView, MarketDeleteView, market_download,MarketDetail
from mysite.views import HomeView
from market.models import Market, Location

app_name = 'market'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('<int:pk>/', MarketDV.as_view(), name='market'),
    path('market_detail/<int:pk>/', MarketDetail.as_view(), name='market_detail'),
    path('market_add/', MarketCreateView.as_view(), name="market_add"),
    path('<int:pk>/market_update/', MarketUpdateView.as_view(), name="market_update"),
    path('<int:pk>/market_delete/', MarketDeleteView.as_view(), name="market_delete"),
    path('market_download/<int:id>', market_download, name="market_download"),

    path('store/<int:pk>/', StoreLV.as_view(), name='store'),
    path('store/<int:fk>/<int:pk>/', StoreDV.as_view(), name='store_detail'),
    path('<int:fk>/store_add/', StoreCreateView.as_view(), name="store_add"),
    path('<int:pk>/store_update/', StoreUpdateView.as_view(), name="store_update"),
    path('<int:pk>/store_delete/', StoreDeleteView.as_view(), name="store_delete"),
    path('store_download/<int:id>', store_download, name="store_download"),
    path('comment/<int:fk>/<int:pk>', store_comment, name='store_comment'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('board/', include('board.urls')),
    path('notice/', include('notice.urls')),
    # 로그인, 로그아웃, 비밀번호 변경 등 담당
    path('accounts/', include('django.contrib.auth.urls')),
    # 회원 가입 및 처리
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(),name='register_done'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/card.html
<div class="support-grid"></div>
<div class="market_list">
  <div class="band">
      {% for m in market_list reversed %}
      {% if forloop.counter < 12 %}
        <div class="item-{{forloop.counter}}">
              <a href="{% url 'market:market' m.id %}" class="card1">
                <!--첨부파일이 없으면 기본 이미지 있으면 대표사진-->
                {% if m.files.get.id %}
                <div class="thumb" style="background-image: url(/market/market_download/{{ m.files.get.id }});"></div>
                {% else %}
                <div class="thumb" style="background-image: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/210284/flex-1.jpg);"></div>
                {% endif %}
                <!--첨부파일이 없으면 기본 이미지 있으면 대표사진 여기까지-->
                <article class="hn">
                  <h2>{{m.market_name}}</h2>
                  <p>{{m.products|linebreaks}}</p>
                  <span>{{m.address|linebreaks}}</span>

                </article>
              </a>
        </div>
      {% endif %}
      {% endfor %}
  </div>
</div>

templates/home.html
{% extends 'base.html' %}
{% block title%}Home{% endblock %}
{% block content%}
<!--이 안에 작성-->



<div class="content hn">
    <h1><i class="fas fa-info-circle"></i>틈새시장</h1>
    <div class="container-fluid">
        <div class="row">
            <!--              1번째 카드-->
            <div class="col-sm-5">
                <div class="card card-chart" style="background-color:rgba(255,255,255,0.9);">
                    <div class="card-header card-header-success" style="text-align:left;">
                        <i class="fas fa-sign-in-alt"></i><span class="hn"> 서울시 전통시장 위치</span></div>
                        <div class="card-body" style="padding:5px;">
                            {% include "map.html" %}
                        </div>
                </div>
            </div>
            <!--              1번째 카드 끝-->
            <!--              2번째 카드-->
            <div class="col-sm-7">
                <div class="card" style="background-color:rgba(134,12,232,0.6);">
                    <div class="card-header card-header-success" style="text-align:left;">
                        <i class="fas fa-sign-in-alt"></i><span class="hn"> 서울시 전통시장 행사 안내</span></div>
                    <div class="card-body table-responsive" style="padding-top:2px;overflow:hidden;">
                        <table class="table table-hover" style="margin-bottom:2px;">
                            <tbody>
                            {% for seoul in html_content %}
                                {% if forloop.counter < 10 %}
                                <tr style="color:white;" onclick="location.href='{{seoul.1}}'">
                                    <td class="target1" style="padding:0.2rem;width:80%;">{{ seoul.0|safe }}</td>
                                    <td class="target1" style="padding:0.1rem;width:20%;">{{ seoul.2|safe }}</td>
                                </tr>
                            {% endif %}
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!--              2번째 카드 끝-->
        </div>
        <div class="row">
            <!--              2번째 열 1번째 카드 시작-->
            <div class="col-sm-12 col-sm-12">
                <div class="card card-chart" style="background-color:rgba(255,255,255,0.9);">
                    <div class="card-header card-header-success" style="text-align:left;"><i
                            class="fas fa-sign-in-alt"></i><span class="hn"> 서울시 전통시장 추천</span></div>
                        <div class="card-body">
                            {% include "card.html" %}
                        </div>
                </div>
            </div>
            <!--              2번째열 1번째 카드 끝-->
            <!--              2번째 열 2번째 카드 시작-->
<!--            <div class="col-lg-6 col-md-12">-->
<!--                <div class="card" style="background-color:rgba(134,12,232,0.6);">-->
<!--                    <div class="card-header card-header-success" style="text-align: left;"><i-->
<!--                            class="fas fa-sign-in-alt"> 네이버 블로그</i>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
            <!--              2번째 열 2번째 카드 끝-->
        </div>
    </div>
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/js/swiper.min.js"></script>

<link rel ="stylesheet" type="text/css" href ="/static/Style.css"/>
<link href="http://fonts.googleapis.com/earlyaccess/hanna.css" rel="stylesheet">
<!--이 안에 작성-->
{% endblock %}

templates/map.html
<style>

.content {
        text-align: center;
        height: 90%;
        width: 90%;
        overflow-y: scroll;
          -ms-overflow-style: none;  /* IE and Edge */
           scrollbar-width: none;  /* Firefox */
    }
.content::-webkit-scrollbar {
         display: none;
    }
.content2 {
        text-align: left;
        height: 100%;
        width: 100%;
        overflow-y: scroll;
          -ms-overflow-style: none;  /* IE and Edge */
           scrollbar-width: none;  /* Firefox */
    }
.content2::-webkit-scrollbar {
         display: none;
    }

.map_wrap {position:relative;width:100%;height:350px;}
.map_wrap, .map_wrap * {margin:0;padding:0;font-family:'Malgun Gothic',dotum,'돋움',sans-serif;font-size:12px;}
.map_wrap a, .map_wrap a:hover, .map_wrap a:active{color:#000;text-decoration: none;}

.customoverlay {position:relative;bottom:85px;border-radius:6px;border: 1px solid #ccc;border-bottom:2px solid #ddd;float:left;}
.customoverlay:nth-of-type(n) {border:0; box-shadow:0px 1px 2px #888;}
.customoverlay a {display:block;text-decoration:none;color:#000;text-align:center;border-radius:6px;font-size:14px;font-weight:bold;overflow:hidden;background: #d95050;background: #d95050 url(https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/arrow_white.png) no-repeat right 14px center;}
.customoverlay .title {display:block;text-align:center;background:#fff;margin-right:35px;padding:10px 15px;font-size:14px;font-weight:bold;}
.customoverlay:after {content:'';position:absolute;margin-left:-12px;left:50%;bottom:-12px;width:22px;height:12px;background:url('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/vertex_white.png')}

</style>

<div class="map_wrap">
    <div id="map" style="width:100%;height:100%;position:relative;overflow:hidden;border-radius:10px;"></div>
</div>

<!--지도용 script 추가-->

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=672f1dc7e3016f169ace1e986e9d359c&libraries=services,clusterer,drawing"></script>
<script>
var mapContainer = document.getElementById('map'), // 지도를 표시할 div
    mapOption = {
        center: new kakao.maps.LatLng(37.560169, 127.013433), // 지도의 중심좌표(청구역)
        level: 8, // 지도의 확대 레벨(서울 다보이게)
        mapTypeId : kakao.maps.MapTypeId.ROADMAP // 지도종류
    };

// 지도를 생성한다
var map = new kakao.maps.Map(mapContainer, mapOption);

// 일반 지도와 스카이뷰로 지도 타입을 전환할 수 있는 지도타입 컨트롤을 생성합니다
var mapTypeControl = new kakao.maps.MapTypeControl();

// 지도에 컨트롤을 추가해야 지도위에 표시됩니다
// kakao.maps.ControlPosition은 컨트롤이 표시될 위치를 정의하는데 TOPRIGHT는 오른쪽 위를 의미합니다
map.addControl(mapTypeControl, kakao.maps.ControlPosition.TOPRIGHT);

// 지도 확대 축소를 제어할 수 있는  줌 컨트롤을 생성합니다
var zoomControl = new kakao.maps.ZoomControl();
map.addControl(zoomControl, kakao.maps.ControlPosition.RIGHT);


// 마커 클러스터러를 생성합니다
var clusterer = new kakao.maps.MarkerClusterer({
    map: map, // 마커들을 클러스터로 관리하고 표시할 지도 객체
    averageCenter: true, // 클러스터에 포함된 마커들의 평균 위치를 클러스터 마커 위치로 설정
    minLevel: 6 // 클러스터 할 최소 지도 레벨
});

/*
// HTML5의 geolocation으로 사용할 수 있는지 확인합니다 (이거 빼면 현위치 없앨 수 있어용)
if (navigator.geolocation) {

    // GeoLocation을 이용해서 접속 위치를 얻어옵니다
    navigator.geolocation.getCurrentPosition(function(position) {

        var lat = position.coords.latitude, // 위도
            lon = position.coords.longitude; // 경도

        var locPosition = new kakao.maps.LatLng(lat, lon), // 마커가 표시될 위치를 geolocation으로 얻어온 좌표로 생성합니다
            message = '<div style="padding:5px;">현재위치</div>'; // 인포윈도우에 표시될 내용입니다

        // 마커와 인포윈도우를 표시합니다
        displayMarker(locPosition, message);

    });

    // 지도에 마커와 인포윈도우를 표시하는 함수입니다
    function displayMarker(locPosition, message) {

        // 마커를 생성합니다
        var marker_present = new kakao.maps.Marker({
            map: map,
            position: locPosition
        });

        var iwContent = message, // 인포윈도우에 표시할 내용
            iwRemoveable = true; // removeable 속성을 ture 로 설정하면 인포윈도우를 닫을 수 있는 x버튼이 표시됩니다

        // 인포윈도우를 생성합니다
        var infowindow = new kakao.maps.InfoWindow({
            content : iwContent,
            removable : iwRemoveable
        });

        // 인포윈도우를 마커위에 표시합니다
        infowindow.open(map, marker_present);

        // 지도 중심좌표를 접속위치로 변경합니다
        map.setCenter(locPosition);
    }

}
*/


var markers = []; // 마커용 빈리스트 생성
var infos = []; // 클릭용 인포 배열 만들어서 하나의 인포만 뜨게 작업용 빈리스트

var positions = [
    {% for m in market_list %}
    {
        content: [
'<div class="content2" style="white-space:nowrap;">',
'   <a href="{% url 'market:market' m.id %}">',
'      <span class="title">{{m.market_name}}</span>',
'      <p>{{m.address|linebreaks}}</p>',
'      <p>{{m.closed_date|linebreaks}}</p>',
'   </a>',
'<b><a href="https://map.kakao.com/link/map/{{m.market_name}},{{m.latitude}},{{m.longitude}}" style="color:blue" target="_blank">큰지도보기</a> | <a href="https://map.kakao.com/link/to/{{m.market_name}},{{m.latitude}},{{m.longitude}}" style="color:blue" target="_blank">길찾기</a></b>',
'</div>'
].join(''),
        latlng: new kakao.maps.LatLng({{m.latitude}}, {{m.longitude}})
    },
    {% endfor %}
];


// 인포윈도우를 표시하는 클로저를 만드는 함수입니다
function makeOverListener(map, marker, infowindow) {
    return function() {
        closeInfoWindow();
        infowindow.open(map, marker);
    };
}

// 인포윈도우를 닫는 클로저를 만드는 함수입니다
function makeOutListener(infowindow) {
    return function() {
        infowindow.close();
    };
}

// 모든 인포 윈도우를 닫는 클로저
function closeInfoWindow() {
    for(var idx=0; idx<infos.length; idx++){
        infos[idx].close();
    }
}





for(var i=0;i<positions.length;i++){
    // 마커가 표시될 위치입니다
    var markerPosition  = positions[i].latlng;

    // 마커를 생성합니다
    var marker = new kakao.maps.Marker({
        position: markerPosition,
        clickable: true
    });

    // 마커가 지도 위에 표시되도록 설정합니다
    marker.setMap(map);
    var iwContent = positions[i].content;
    iwPosition = markerPosition //인포윈도우 표시 위치입니다

    // 인포윈도우를 생성합니다
    var infowindow = new kakao.maps.InfoWindow({
        position : iwPosition,
        content : iwContent,
        removable : true
    });


    markers.push(marker);
    infos.push(infowindow);


    kakao.maps.event.addListener(marker, 'click', makeOverListener(map, marker, infowindow));
    //kakao.maps.event.addListener(marker, 'click', makeOutListener(infowindow));
    //kakao.maps.event.addListener(marker, 'mouseout', makeOutListener(infowindow));



}

// 클러스터러에 마커들을 추가합니다
clusterer.addMarkers(markers);



</script>

templates/menu.html
{% block extra-style %}
<style type="text/css">
	@media (min-width: 992px){
		.dropdown-menu .dropdown-toggle:after{
			border-top: .3em solid transparent;
		    border-right: 0;
		    border-bottom: .3em solid transparent;
		    border-left: .3em solid;
		}

		.dropdown-menu .dropdown-menu{
			margin-left:0; margin-right: 0;
		}

		.dropdown-menu li{
			position: relative;
		}
		.nav-item .submenu{
			display: none;
			position: absolute;
			left:100%; top:-7px;
		}
		.nav-item .submenu-left{
			right:100%; left:auto;
		}

		.dropdown-menu > li:hover{ background-color: #f1f1f1 }
		.dropdown-menu > li:hover > .submenu{
			display: block;
		}
	}



</style>
{% endblock %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Niche Market</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="">게시판</a></li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown"> 점포안내 </a>
                <ul class="dropdown-menu">
                    {% for i in location %}
                    <li><a class="dropdown-item dropdown-toggle" href="#"> {{i.location}} </a>
                        <ul class="submenu dropdown-menu">
                            {% for x in market_list %}
                            {% if x.location_id == i.id %}
                            <li><a class="dropdown-item" href="{% url 'market:market' x.id %}">{{x.market_name}}</a>
                            </li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </li>
                    {% endfor %}
                </ul>
            </li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'market:market_add' %}">시장추가</a></li>

            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white"
                   href="">로그인</a></li>



        </ul>
        <form class="form-inline my-2" action="" method="post"> {% csrf_token %}
            <input class="form-control mr-sm-2" type="search"
                   placeholder="global search" name="search_word">
        </form>
    </div>
</nav>